### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by ahmednooor** [Blunk-electronic/ET#1]
Hello, I hope you are fine.
I read about website in collaboration section of readme.
I can help with a static website. Let me know if it is still needed.
Thank You.

**Comment by MarioBlunk** [comment]
Hello ahmednooor,
I'm so sorry for my very very late reply. Just now I'm reading your full message. Over the last three years I've been very busy with lots of geometry problems (like polygon processing). Now the projects seems to be going into the right direction. So If you are still interested in setting up a nice website, your help is highly welcome.
Best, 
Mario

**Comment by ahmednooor** [comment]
Hi Mario,
Sorry for getting back late. Although I can't commit fully due to different commitments in life, but please feel free to share some layout sketches and I will try my best to be helpful where I can.
Thank you & best,
Ahmed

**Comment by MarioBlunk** [comment]
Ahmed, 
I haven't find the time and energy to prepare some nice screenshots of a simple demo project. The project has reached the point at which the users can create library models, schematics and board layouts. Some library models already available.  
 So if you or someone else is willing to play with ET a bit, please feel free. Otherwise some time will pass until I come back to this part of the project.
Thank you for your offer,
Mario

**Comment by ahmednooor** [comment]
Hey, sorry, due to lack of availibility, I am closing this issue. Wish you all the best.
